print("   o     o")
print("   |_____|")
print("   |0   0|    __________________")
print("   |_\_/_|__ / Hello! I am Ian  |")
print("   __| |__ \ the Alien!!!!!   |")
print("o==|     |==o \----------------/")
print("   |     |")
print("   -------")
print("    || ||")
print("    || ||")
print("     0 0")