print ("Hello! My name is Ryder what's your name?")
name = input("Hello! My name is Ryder what's your name?") 
print (f"hello{name} welcome to my project!")
print (f"I have many things to share with you{name}!")
print ("I play guitar! Whats your favorite instrument?")
instrument = input("I play guitar! Whats your favorite instrument?")
print (f"The{instrument} is certainly a good one!")
print ("whats your favorite movie?")
movie = input("whats your favorite movie?")
print (f"Nice, {movie} sounds like a thrilling movie!") 
print ("My favorite movie is The Shining!") 
print ("101011100111000111000110 ERROR")
print ("just kidding lol")
print (f"Anyways{name}, do you like this quiz?")
quiz = input(f"Anyways{name}, do you like this quiz?")
print ("Assuming you said yes, thank you very much!")
print ("to finish this quiz off lets play rock paper scissors choose one of the them")
them = input("to finish this quiz off lets play rock paper scissors choose one of the them")
print ("dang you chose that one?! I lost...")
print (f"well I hope you have a good day{name}")
print ("bye!!!!!!!")